# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-11 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_user_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tenant',
            field=models.BooleanField(default=True),
        ),
    ]
