# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-22 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_auto_20190722_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='owner',
        ),
        migrations.AlterField(
            model_name='house',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='building_houses', to='agent.Building'),
        ),
        migrations.AlterField(
            model_name='house',
            name='occupant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_house', to='agent.Tenant'),
        ),
    ]
